SELECT * FROM spr.mensajeria;
insert into spr.mensajeria (id_mensaje, mensajes) values (1, 'quiero cotizar un servicio');
insert into spr.mensajeria (id_mensaje, mensajes) values (2, 'ya realize el pago '); 
insert into spr.mensajeria (id_mensaje, mensajes) values (3, 'quiero cotizar un servicio'); 
insert into spr.mensajeria (id_mensaje, mensajes) values (4, 'que precio tendria? '); 
insert into spr.mensajeria (id_mensaje, mensajes) values (5, 'quiero cotizar un servicio'); 
insert into spr.mensajeria (id_mensaje, mensajes) values (6, 'que precio tendria?'); 
insert into spr.mensajeria (id_mensaje, mensajes) values (7, 'quiero cotizar un servicio'); 
insert into spr.mensajeria (id_mensaje, mensajes) values (8, 'que precio tendria? '); 
insert into spr.mensajeria (id_mensaje, mensajes) values (9, 'quiero cotizar un servicio'); 
insert into spr.mensajeria (id_mensaje, mensajes) values (10, 'ya realize el pago'); 
insert into spr.mensajeria (id_mensaje, mensajes) values (11, 'quiero cotizar un servicio'); 
insert into spr.mensajeria (id_mensaje, mensajes) values (12, 'que precio tendria?'); 
insert into spr.mensajeria (id_mensaje, mensajes) values (13, 'quiero cotizar un servicio'); 
insert into spr.mensajeria (id_mensaje, mensajes) values (14, 'ya realize el pago');
insert into spr.mensajeria (id_mensaje, mensajes) values (15, 'quiero cotizar un servicio');  